language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: N9rPl8P6MpJW7CLrv5R5vcICQR4Xo4qqqEzPpwLdI3NhlnZ1RCKo7ywthtLJ+QlZQgst5BDbdKry3BbOynsfk5xzpRpDxIvkPHGmu0UniiJl4pW2drNC7fAESHIGzMMqwSRqVfGrIPuHsx2xQ5vdIazJqz84/xrHDOTs5Gl+WODv/QHTkrYO15axgOsRyXMyoe6l3kRBJTb3zticjN1EPoPjcIihLJ4UJIZObIZ9jSdbdLJ70mBqKq7yavmJifbrJDSmygJGGgL6jlcTCjY8QamQNXqO88mPzxXunp7BxFUD1Kr+wfkfWezaSHcURk2WC3zZpzGHD7EYA2LksFSQK1GcdlrcjFVfIMVxetwf7kZ0M3mIdsY3KGDAj11u+rAg3l0s5VZX7wodjp6cMAlCy5k9qkrHNtt+i2Hg+zkNYR/T5q4pwi2tutuJP29K2DbDSxLEanBs7NkuopaLDtb5yojmuxH52/rdA3pU0WeYero4Aegg0mMe9Ymrbt7pjCRm69TbesAmVojOgsuOQeJOZFgSHAYAFyzbJP9ckd28gXLZXIkeZFcDPCt4rxuWkzxUhFelP2kyDG15sqdM04F00Jj3qO/Znkt6bF7YqN15FXdiQeOW+KlKpkWLTMr4hcHoz9mfjGAzZvAezU/pykYRBU/AztB3BPmr0XkvlWihk4c=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: Pz1kCr86Kvf3fTkCxonLndm5ubPlBdW8/D9Pi4CWfFjlmJzzRZdo6+apAkMylCPA8dvgdw0rVoOeJRzq3Q08YGtcUYJsO6jQze+mw/4qK3spTK959cW+mVipRuf/FVehCCV/NM5qM3LspEYAnsU3MYEeic3qrInjyJEmvIMputXyzwiQ5sY3BwRM2NO/Qmho2Yy9B1dzx3hVjp4uZe6hclT1VyFEiJUtFUxZfXHFb5Ef1Or/G8XkGkg0ULRwGmyh3D8tYVybt6E9O4tZwiN0MGvPJ2oH3FKhbG0HlzhVKI57YrmxWDu5EVXnBTsBmdBr1UIC3swC3sOJFxkxZyZN68JjavR/hnCt0sBHrmhX3jkzL2vlfoikNeAGXLmZzbtqy0eU2IINWv97ce2LeboKImlvSaQHKixxv9hZCdSzTMSGy6ZtxMI7G4Mql4SGBhNocOuHvNVmLuuITA1WqBNAV7bahzM1dIPeS6n63i7oBZS67ZOFsNJ1vQV1qU/Rvb8TUhsdCbfvBLJC09Nn6P0Jg6CTn+2/lF6vl3HSDQw0gAAA4Eh9BOIvi6FgPWCuR4DChJluOVW65zRuY+dVzM6coqoRnNT8kzCgUyvLKgxplDVOCu7JlFkMA8+Qx/joBl7eTJONIeor++CciIR5pd8OaOfe7oBwpdIl19vPnelVZL8=
sudo: false
